//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listing
    {
        public int ListingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public string Title { get; set; }
        public Nullable<int> VIN { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> MakeID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public string Trim { get; set; }
        public Nullable<int> BodyStyleID { get; set; }
        public Nullable<int> TransmissionID { get; set; }
        public Nullable<bool> ShowVIN { get; set; }
        public Nullable<bool> IsCertified { get; set; }
        public Nullable<bool> IsETested { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> KM { get; set; }
        public Nullable<int> BodyColorID { get; set; }
        public Nullable<int> InteriorColorID { get; set; }
        public Nullable<int> DoorCountID { get; set; }
        public Nullable<int> PassengerCountID { get; set; }
        public Nullable<int> DriveTrainID { get; set; }
        public string Engine { get; set; }
        public Nullable<int> CylinderCount { get; set; }
        public Nullable<int> FuelTypeID { get; set; }
        public Nullable<int> StatusTypeID { get; set; }
        public string Location { get; set; }
    
        public virtual StatusType StatusType { get; set; }
    }
}
